language: php

services:
  - mongodb

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mongo admin --eval 'db.addUser("root", "root");'
  - phpenv config-add .travis.php.ini
  - composer --prefer-source --dev install

script: phpunit --coverage-text --verbose