language: php

services: mongodb

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer selfupdate

install:
  - composer update --prefer-dist --no-interaction

script: phpunit --coverage-text --verbose
